http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  orders:
    host: localhost
    paths: '/orders*'
    methods: 'GET,POST,PUT'
  payments:
    host: localhost
    paths: '/payments*'
    methods: 'GET,POST,PUT'
  products:
    host: localhost
    paths: '/products*'
    methods: 'GET,POST,PUT'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  ordersService:
    url: 'http://localhost:4001'
  paymentsService:
    url: 'http://localhost:4002'
  productsService:
    url: 'http://localhost:4003'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  orders:
    apiEndpoints:
      - orders
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: ordersService
              changeOrigin: true
  payments:
    apiEndpoints:
      - payments
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: paymentsService
              changeOrigin: true
  products:
    apiEndpoints:
      - products
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: productsService
              changeOrigin: true
